name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: '4.1'}
          - {os: macos-latest, r: '4.1'}
          - {os: windows-latest, r: '4.1'}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools
            testthat
            httptest
            covr
            lintr
      - name: Lint
        run: Rscript -e 'lintr::lint_package()'
      - name: R CMD check
        run: Rscript -e 'devtools::check(args = c("--no-manual", "--as-cran"))'
      - name: Test coverage and upload
        run: Rscript -e 'covr::codecov()'